# name: Node.js CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - run: npm install
#       - run: npm test -- --coverage
#       - run: |
#           COVERAGE=$(node -e "console.log(require('./coverage/coverage-summary.json').total.lines.pct)")
#           if [ $COVERAGE -lt 20 ]; then
#             echo "Test coverage is below 20%" && exit 1
#           fi